#!/bin/bash
juloadconfig=true
prompt=false
#getopts
while getopts t:c:p FLAG; do
	case $FLAG in
		t) 
			jutitle="$OPTARG" #TODO: create an array; append -t: to array.
			printf "%s\n" "-t: is not yet implemented" >&2
			;;
		c)
			juloadconfig=false
			source "$OPTARG"
			;;
		p)
			prompt=true
			;;
	esac
done
shift $((OPTIND-1))
#load config. Do this after, in case the user supplied a special config file.
if $juloadconfig && [ -f ~/.config/jekyll-upload.conf ]
then
	source ~/.config/jekyll-upload.conf
else
	junossh=true
	jubuild=false
fi
while [ "$#" -ne 0 ]
do
	FILE=$1
	judatestamp=$(date +%Y-%m-%d)
	if $prompt; then
		read -p "Title for $1? >" title
	else
		title=$(sed -ne's/title: "\([^"]*\).*/\1/p' <"$FILE")
	fi
	if [ "$title" = "" ]; then title="Untitled"; fi
	sanetitle=$(printf "%s" "$title" | tr '[:upper:]' '[:lower:]' | sed -e 's/ /-/g' -e's/[^-a-zA-Z0-9]//g')
	finaltitle=$(printf "%s-%s.%s" "$judatestamp" "$sanetitle" "${FILE##*.}")
	if ! $junossh; then
		scparg=$(printf "%s@%s:%s/%s" "$jusshname" "$jusshserver" "$jusshdir" "$finaltitle")
		scp $FILE $scparg
	fi
	shift
done
if $jubuild && ! $junossh; then
	ssh $jusshname@$jusshserver "cd $jbdir && jekyll build $jbargs"
fi
